services:
  myhomeweb:
    image: ghcr.io/maximosro/myhomeweb-go:latest
    restart: always
    network_mode: host
    environment:
      - PORT=19484
      - DB_PATH=/data/myhomeweb.db
    volumes:
      - myhomeweb_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.myhomeweb.rule=Host(`home.srv1158554.hstgr.cloud`)
      - traefik.http.routers.myhomeweb.tls=true
      - traefik.http.routers.myhomeweb.entrypoints=web,websecure
      - traefik.http.routers.myhomeweb.tls.certresolver=letsencrypt
      - traefik.http.services.myhomeweb.loadbalancer.server.url=http://127.0.0.1:19484

volumes:
  myhomeweb_data:
